import type { Project, Issue } from "@/types"

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Application Web",
    platform: "React",
    status: "active",
    errorCount: 186,
    lastSeen: "2024-01-15T10:30:00Z",
    team: ["Alice Johnson", "Bob Smith", "Charlie Davis", "Diana Wilson"],
  },
  {
    id: "2",
    name: "API Backend",
    platform: "Node.js",
    status: "active",
    errorCount: 89,
    lastSeen: "2024-01-15T09:15:00Z",
    team: ["Eve Taylor", "Frank Miller", "Grace Lee"],
  },
  {
    id: "3",
    name: "Application Mobile",
    platform: "React Native",
    status: "active",
    errorCount: 34,
    lastSeen: "2024-01-14T16:45:00Z",
    team: ["Henry Brown", "Ivy Chen", "Jack Wilson"],
  },
  {
    id: "4",
    name: "Service Analytics",
    platform: "Python",
    status: "active",
    errorCount: 12,
    lastSeen: "2024-01-14T14:20:00Z",
    team: ["Kate Davis", "Liam Johnson"],
  },
  {
    id: "5",
    name: "Microservice Auth",
    platform: "Go",
    status: "active",
    errorCount: 8,
    lastSeen: "2024-01-15T08:30:00Z",
    team: ["Mike Wilson", "Nina Garcia"],
  },
  {
    id: "6",
    name: "Data Pipeline",
    platform: "Python",
    status: "warning",
    errorCount: 45,
    lastSeen: "2024-01-13T12:15:00Z",
    team: ["Oscar Martinez", "Paula Rodriguez"],
  },
  {
    id: "7",
    name: "Frontend Admin",
    platform: "Vue.js",
    status: "active",
    errorCount: 23,
    lastSeen: "2024-01-15T07:45:00Z",
    team: ["Quinn Taylor", "Rachel Green"],
  },
  {
    id: "8",
    name: "Payment Service",
    platform: "Java",
    status: "active",
    errorCount: 5,
    lastSeen: "2024-01-15T11:20:00Z",
    team: ["Sam Brown", "Tina White"],
  },
  {
    id: "9",
    name: "Notification Service",
    platform: "Node.js",
    status: "active",
    errorCount: 67,
    lastSeen: "2024-01-14T18:30:00Z",
    team: ["Uma Patel", "Victor Kim"],
  },
  {
    id: "10",
    name: "Search Engine",
    platform: "Elasticsearch",
    status: "active",
    errorCount: 15,
    lastSeen: "2024-01-15T06:10:00Z",
    team: ["Will Thompson", "Xara Lopez"],
  },
  {
    id: "11",
    name: "CDN Service",
    platform: "CloudFlare",
    status: "active",
    errorCount: 3,
    lastSeen: "2024-01-15T09:45:00Z",
    team: ["Yuki Tanaka", "Zoe Adams"],
  },
  {
    id: "12",
    name: "Legacy System",
    platform: "PHP",
    status: "inactive",
    errorCount: 0,
    lastSeen: "2024-01-10T14:20:00Z",
    team: ["Alex Morgan"],
  },
]

export const mockIssues: Issue[] = [
  {
    id: "1",
    title: "TypeError: Cannot read property 'map' of undefined",
    message: "Erreur lors du rendu de la liste des utilisateurs dans le composant UserList",
    level: "error",
    status: "unresolved",
    count: 186,
    userCount: 45,
    firstSeen: "2024-01-14T08:30:00Z",
    lastSeen: "2024-01-15T10:30:00Z",
    assignee: "Alice Johnson",
    project: "Application Web",
  },
  {
    id: "2",
    title: "Database connection timeout",
    message: "Timeout lors de la connexion à la base de données PostgreSQL",
    level: "error",
    status: "unresolved",
    count: 89,
    userCount: 23,
    firstSeen: "2024-01-15T09:00:00Z",
    lastSeen: "2024-01-15T09:45:00Z",
    assignee: "Eve Taylor",
    project: "API Backend",
  },
  {
    id: "3",
    title: "Slow API response time",
    message: "Les requêtes vers /api/users prennent plus de 2 secondes",
    level: "warning",
    status: "resolved",
    count: 234,
    userCount: 67,
    firstSeen: "2024-01-12T14:20:00Z",
    lastSeen: "2024-01-14T16:30:00Z",
    assignee: "Bob Smith",
    project: "API Backend",
  },
  {
    id: "4",
    title: "Memory usage spike",
    message: "Utilisation mémoire élevée détectée sur le serveur de production",
    level: "warning",
    status: "unresolved",
    count: 45,
    userCount: 12,
    firstSeen: "2024-01-15T07:15:00Z",
    lastSeen: "2024-01-15T08:20:00Z",
    assignee: "Charlie Davis",
    project: "Data Pipeline",
  },
  {
    id: "5",
    title: "Authentication token expired",
    message: "Tokens JWT expirant prématurément causant des déconnexions",
    level: "error",
    status: "unresolved",
    count: 67,
    userCount: 34,
    firstSeen: "2024-01-14T18:30:00Z",
    lastSeen: "2024-01-15T11:20:00Z",
    assignee: "Mike Wilson",
    project: "Microservice Auth",
  },
]

export const mockChartData = {
  errors: [
    { date: "2024-01-08", count: 45 },
    { date: "2024-01-09", count: 67 },
    { date: "2024-01-10", count: 23 },
    { date: "2024-01-11", count: 89 },
    { date: "2024-01-12", count: 156 },
    { date: "2024-01-13", count: 134 },
    { date: "2024-01-14", count: 198 },
    { date: "2024-01-15", count: 186 },
  ],
  performance: [
    { name: "API", value: 35 },
    { name: "Frontend", value: 25 },
    { name: "Database", value: 20 },
    { name: "Cache", value: 12 },
    { name: "CDN", value: 8 },
  ],
}
