name: Build & Test BugTracker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 📥 Cloner le code
      uses: actions/checkout@v3

    - name: 🔧 Installer Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 📦 Build avec Maven
      run: mvn -B package --file service-ingestion/service-ingestion/pom.xml
     
    - name: ✅ Lancer les tests
      run: mvn test --file service-ingestion/service-ingestion/pom.xml -Dspring.profiles.active=test