name: Build & Test BugTracker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1) Récupère le code
    - name: 📥 Cloner le code
      uses: actions/checkout@v3

    # 2) Installe Java 17
    - name: 🔧 Installer Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3) Compile le micro-service ingestion
    - name: 📦 Build service-ingestion
      run: mvn -B package --file service-ingestion/pom.xml

    # 4) Exécute les tests unitaires
    - name: ✅ Tests service-ingestion
      run: mvn test --file service-ingestion/pom.xml -Dspring.profiles.active=test

    - name: 📦 Build service-traitement
      run: mvn -B package --file service-traitement/pom.xml

    - name: ✅ Tests service-traitement
      run: mvn test --file service-traitement/pom.xml -Dspring.profiles.active=test
